name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present

      - name: deploy
        uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: ${{secrets.EMAIL_HEROKU}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          procfile: "web: npm start"
          dynamicFiles: false
          justlogin: true
